Repository roclark/sportsipy, pull requests merged in 2019-11, with the labels that each got.

#253 Trigger actions on Pull Requests
  .github/workflows/pushtests.yml
Labels: bug

#250 Update NFL season URL
  sportsreference/nfl/constants.py
Labels: bug

#246 nfl.schedule.Game.result return win/loss/tie/unknown correctly
  sportsreference/constants.py
  sportsreference/nfl/schedule.py
  tests/unit/test_nfl_schedule.py
Labels: bug

#258 Fix incorrect home records in NBA boxscores
  sportsreference/nba/boxscore.py
  sportsreference/nba/constants.py
  sportsreference/utils.py
Labels: bug

#260 Fix encoding issues with player names in tests
  tests/exhaustive/mlb_tests.py
  tests/exhaustive/nba_tests.py
Labels: bug

#273 Remove limit on parallel jobs
  .github/workflows/pushtests.yml
Labels: enhancement

#278 Add College Football Playoff (CFP) rankings
  sportsreference/ncaaf/constants.py
  sportsreference/ncaaf/rankings.py
  tests/integration/rankings/ncaaf/2017-polls.html
  tests/integration/rankings/test_ncaaf_rankings.py
Labels: enhancement

#280 Support Python 3.8
  .github/workflows/exhaustive.yml
  .github/workflows/pushtests.yml
  setup.py
Labels: dependency update

#282 Add game summary for NCAAF boxscores
  sportsreference/ncaaf/boxscore.py
  sportsreference/ncaaf/constants.py
  tests/integration/boxscore/test_ncaaf_boxscore.py
  tests/unit/test_ncaaf_boxscore.py
Labels: enhancement

#287 Add game summary for NFL boxscores
  sportsreference/nfl/boxscore.py
  sportsreference/nfl/constants.py
  tests/integration/boxscore/test_nfl_boxscore.py
  tests/unit/test_nfl_boxscore.py
Labels: enhancement
