Repository roclark/sportsipy, pull requests merged in 2020-04, with the labels that each got.

#366 Skip NCAAB teams without stat pages
  sportsreference/ncaab/teams.py
  tests/integration/teams/test_ncaab_integration.py
Labels: bug

#367 Convert MLB innings pitched to float
  sportsreference/mlb/boxscore.py
Labels: enhancement

#369 Switch MLB Boxscore player teams
  sportsreference/mlb/boxscore.py
Labels: bug

#371 Remove unused dependencies
  requirements.txt
Labels: dependency update

#377 Fix issue pulling NFL rosters
  sportsreference/nfl/roster.py
Labels: bug

#378 Fix NFL datetimes for playoff games
  sportsreference/nfl/schedule.py
Labels: bug

#380 Handle football HTTP errors
  sportsreference/fb/roster.py
  sportsreference/fb/schedule.py
  sportsreference/fb/team.py
  tests/unit/test_fb_roster.py
  tests/unit/test_fb_schedule.py
  tests/unit/test_fb_team.py
Labels: bug

#381 add kicking stats to ncaaf players
  sportsreference/ncaaf/player.py
  sportsreference/ncaaf/roster.py
  tests/integration/roster/ncaaf/jd-dillinger-1.html
  tests/integration/roster/test_ncaaf_roster.py
Labels: enhancement

#386 Add __init__.py to sportsreference.fb
  sportsreference/fb/__init__.py
Labels: bug

#388 Remove universal wheels
  .github/workflows/pushtests.yml
Labels: deprecation warning

#392 Fix issue pulling football schedules and rosters
  sportsreference/fb/team.py
  tests/unit/test_fb_team.py
Labels: bug

#397 Use tokenless Codecov action
  .github/workflows/pushtests.yml
Labels: enhancement

#395 Remove attempted_passes from NCAAF
  sportsreference/ncaaf/player.py
  sportsreference/ncaaf/roster.py
  tests/unit/test_ncaaf_boxscore.py
  tests/unit/test_ncaaf_roster.py
Labels: deprecation warning

#398 Add datetime property to NFL boxscores
  sportsreference/nfl/boxscore.py
  tests/integration/boxscore/test_nfl_boxscore.py
  tests/unit/test_nfl_boxscore.py
Labels: enhancement

#399 Handle missing player weights throwing errors
  sportsreference/mlb/roster.py
  sportsreference/nba/roster.py
  sportsreference/nfl/roster.py
  sportsreference/nhl/roster.py
  tests/unit/test_mlb_roster.py
  tests/unit/test_nba_roster.py
  tests/unit/test_nfl_roster.py
  tests/unit/test_nhl_roster.py
Labels: bug

#394 NBA: adding TypeError checks around operations
  sportsreference/nba/boxscore.py
  sportsreference/nba/roster.py
  tests/unit/test_nba_boxscore.py
Labels: bug

#363 Enable NBA Team to be directly accessible
  docs/nba.rst
  sportsreference/nba/nba_utils.py
  sportsreference/nba/teams.py
  tests/integration/teams/test_nba_integration.py
Labels: enhancement

#409 Fix issue with FB schedule using invalid date
  tests/integration/schedule/test_fb_schedule.py
Labels: bug

#390 Enable MLB Team to be directly accessible
  docs/mlb.rst
  sportsreference/mlb/mlb_utils.py
  sportsreference/mlb/teams.py
  tests/integration/teams/test_mlb_integration.py
Labels: enhancement

#404 Enable NCAAB Team to be directly accessible
  docs/ncaab.rst
  sportsreference/ncaab/ncaab_utils.py
  sportsreference/ncaab/teams.py
  tests/integration/teams/test_ncaab_integration.py
Labels: enhancement

#405 Enable NCAAF Team to be directly accessible
  docs/ncaaf.rst
  sportsreference/ncaaf/ncaaf_utils.py
  sportsreference/ncaaf/teams.py
  tests/integration/roster/test_ncaaf_roster.py
  tests/integration/teams/test_ncaaf_integration.py
Labels: enhancement

#406 Enable NFL Team to be directly accessible
  docs/nfl.rst
  sportsreference/nfl/nfl_utils.py
  sportsreference/nfl/teams.py
  tests/integration/roster/test_nfl_roster.py
  tests/integration/teams/test_nfl_integration.py
Labels: enhancement

#407 Enable NHL Team to be directly accessible
  docs/nhl.rst
  sportsreference/nhl/nhl_utils.py
  sportsreference/nhl/teams.py
  tests/integration/roster/test_nhl_roster.py
  tests/integration/teams/test_nhl_integration.py
Labels: enhancement
