Repository roclark/sportsipy, pull requests merged in 2022-03, with the labels that each got.

#589 fewer lines of code
  sportsipy/fb/fb_utils.py
Labels: enhancement

#605 Update squad_ids.py
  sportsipy/fb/squad_ids.py
Labels: bug

#716 Remove windows-2016 OS from GitHub Actions
  .github/workflows/pushtests.yml
Labels: dependency update

#715 Update fumbles recovered for TD
  sportsipy/nfl/constants.py
  tests/integration/roster/test_nfl_roster.py
Labels: bug
