Repository roclark/sportsipy, pull requests merged in 2022-02, with the labels that each got.

#685 Fix empty NFL Rosters
  sportsipy/nfl/roster.py
Labels: bug

#702 Drop support for Python 3.6
  .github/workflows/exhaustive.yml
  .github/workflows/pushtests.yml
  setup.py
Labels: deprecation warning

#700 Update README indicating development status
  README.rst
Labels: documentation

#703 Remove dev-dependencies from requirements.txt
  .github/workflows/pushtests.yml
  requirements.txt
  setup.py
Labels: dependency update

#705 Revert numpy version for Python 3.7 support
  requirements.txt
Labels: dependency update

#704 Fix issue with NFL tests
  tests/integration/roster/nfl/2018_roster.htm
Labels: bug
